#!/bin/bash

# Create the index.html file with the specified title
echo "<!DOCTYPE html>" > index.html
echo "<html>" >> index.html
echo "<head>" >> index.html
echo "  <title>My Website</title>" >> index.html
echo "</head>" >> index.html
echo "<body>" >> index.html
echo "  <h1>Welcome to My Website!</h1>" >> index.html
echo "  <p>This is a simple HTML file generated by a GitHub Action.</p>" >> index.html
echo "</body>" >> index.html
echo "</html>" >> index.html

echo "index.html generated successfully!"
