name: Build and Deploy
on:
  push:
   branches:
   - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
        -name: Checkout
        uses: actions/checkout@v2

    -name: Configure Node
  use: actions/setup-node@v1
  with:
   node-version: '12.18.4'
