name: Generate and Deploy HTML

on:
  push:
    branches:
      - main # Or your default branch like 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate HTML File
        run: bash ./generate_html.sh # Execute the script to create index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # A popular action for deploying to GH Pages
        with:
          
          publish_dir: . # Deploy the current directory, which contains index.html
          # Keep this commented out unless you want a different branch for pages
          # publish_branch: gh-pages
